### ISSUE TITLE
can you help me - error

### ISSUE THREAD

**Issue by nikolaiusa** [s0md3v/sd-webui-roop#2] opened 2023-06-18 14:57 UTC
Error running install.py for extension C:\Users\SD\stable-diffusion-webui\extensions\sd-webui-roop.
Command: "C:\Users\SD\stable-diffusion-webui\venv\Scripts\python.exe" "C:\Users\SD\stable-diffusion-webui\extensions\sd-webui-roop\install.py"
Error code: 1
stdout: Check roop requirements
Install insightface==0.7.3
Installing sd-webui-roop requirement: insightface==0.7.3
Install onnx==1.14.0
Installing sd-webui-roop requirement: onnx==1.14.0
Install onnxruntime==1.15.0
Installing sd-webui-roop requirement: onnxruntime==1.15.0
Install tensorflow==2.12.0
Installing sd-webui-roop requirement: tensorflow==2.12.0
Couldn't install sd-webui-roop requirement: tensorflow==2.12.0.
Command: "C:\Users\SD\stable-diffusion-webui\venv\Scripts\python.exe" -m pip install tensorflow==2.12.0 --prefer-binary
Error code: 1
stdout: Collecting tensorflow==2.12.0
  Using cached tensorflow-2.12.0-cp310-cp310-win_amd64.whl (1.9 kB)
Requirement already satisfied: tensorflow-intel==2.12.0 in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from tensorflow==2.12.0) (2.12.0)
Requirement already satisfied: absl-py>=1.0.0 in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0) (1.6.3)
Requirement already satisfied: flatbuffers>=2.0 in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0) (23.3.3)
Requirement already satisfied: gast<=0.4.0,>=0.2.1 in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0) (0.4.0)
Requirement already satisfied: google-pasta>=0.1.1 in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0) (0.2.0)
Requirement already satisfied: h5py>=2.9.0 in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0) (3.8.0)
Requirement already satisfied: jax>=0.3.15 in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0) (0.4.12)
Requirement already satisfied: libclang>=13.0.0 in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0) (16.0.0)
Requirement already satisfied: numpy<1.24,>=1.22 in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0) (1.23.5)
Requirement already satisfied: opt-einsum>=2.3.2 in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0) (3.3.0)
Requirement already satisfied: packaging in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0) (23.0)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0) (3.20.3)
Requirement already satisfied: setuptools in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0) (67.6.1)
Requirement already satisfied: six>=1.12.0 in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0) (1.16.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0) (2.2.0)
Requirement already satisfied: typing-extensions>=3.6.6 in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0) (4.5.0)
Requirement already satisfied: wrapt<1.15,>=1.11.0 in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0) (1.14.1)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0) (1.51.3)
Collecting tensorboard<2.13,>=2.12 (from tensorflow-intel==2.12.0->tensorflow==2.12.0)
  Using cached tensorboard-2.12.3-py3-none-any.whl (5.6 MB)
Collecting tensorflow-estimator<2.13,>=2.12.0 (from tensorflow-intel==2.12.0->tensorflow==2.12.0)
  Using cached tensorflow_estimator-2.12.0-py2.py3-none-any.whl (440 kB)
Collecting keras<2.13,>=2.12.0 (from tensorflow-intel==2.12.0->tensorflow==2.12.0)
  Using cached keras-2.12.0-py2.py3-none-any.whl (1.7 MB)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0) (0.31.0)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from astunparse>=1.6.0->tensorflow-intel==2.12.0->tensorflow==2.12.0) (0.38.4)
Requirement already satisfied: ml-dtypes>=0.1.0 in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from jax>=0.3.15->tensorflow-intel==2.12.0->tensorflow==2.12.0) (0.2.0)
Requirement already satisfied: scipy>=1.7 in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from jax>=0.3.15->tensorflow-intel==2.12.0->tensorflow==2.12.0) (1.10.1)
Requirement already satisfied: google-auth<3,>=1.6.3 in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0->tensorflow==2.12.0) (2.16.2)
Collecting google-auth-oauthlib<1.1,>=0.5 (from tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0->tensorflow==2.12.0)
  Using cached google_auth_oauthlib-1.0.0-py2.py3-none-any.whl (18 kB)
Requirement already satisfied: markdown>=2.6.8 in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0->tensorflow==2.12.0) (3.4.1)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0->tensorflow==2.12.0) (2.25.1)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0->tensorflow==2.12.0) (0.7.1)
Requirement already satisfied: werkzeug>=1.0.1 in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0->tensorflow==2.12.0) (2.2.3)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0->tensorflow==2.12.0) (5.3.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0->tensorflow==2.12.0) (0.2.8)
Requirement already satisfied: rsa<5,>=3.1.4 in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0->tensorflow==2.12.0) (4.9)
Requirement already satisfied: requests-oauthlib>=0.7.0 in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from google-auth-oauthlib<1.1,>=0.5->tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0->tensorflow==2.12.0) (1.3.1)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0->tensorflow==2.12.0) (4.0.0)
Requirement already satisfied: idna<3,>=2.5 in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0->tensorflow==2.12.0) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0->tensorflow==2.12.0) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0->tensorflow==2.12.0) (2022.12.7)
Requirement already satisfied: MarkupSafe>=2.1.1 in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from werkzeug>=1.0.1->tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0->tensorflow==2.12.0) (2.1.2)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0->tensorflow==2.12.0) (0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.1,>=0.5->tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0->tensorflow==2.12.0) (3.2.2)
Installing collected packages: tensorflow-estimator, keras, google-auth-oauthlib, tensorboard, tensorflow
  Attempting uninstall: tensorflow-estimator
    Found existing installation: tensorflow-estimator 2.10.0
    Uninstalling tensorflow-estimator-2.10.0:
      Successfully uninstalled tensorflow-estimator-2.10.0
  Attempting uninstall: keras
    Found existing installation: keras 2.10.0
    Uninstalling keras-2.10.0:
      Successfully uninstalled keras-2.10.0
  Attempting uninstall: google-auth-oauthlib
    Found existing installation: google-auth-oauthlib 0.4.6
    Uninstalling google-auth-oauthlib-0.4.6:
      Successfully uninstalled google-auth-oauthlib-0.4.6
  Attempting uninstall: tensorboard
    Found existing installation: tensorboard 2.10.1
    Uninstalling tensorboard-2.10.1:
      Successfully uninstalled tensorboard-2.10.1
  Attempting uninstall: tensorflow
    Found existing installation: tensorflow 2.10.1
    Uninstalling tensorflow-2.10.1:
      Successfully uninstalled tensorflow-2.10.1

stderr: ERROR: Could not install packages due to an OSError: [WinError 5]   : 'C:\\Users\\SD\\AppData\\Local\\Temp\\pip-uninstall-dlwz0m5i\\python\\flags_pybind.pyd'
Check the permissions.

Warning: Failed to install tensorflow==2.12.0, roop will not work.

stderr: Traceback (most recent call last):
  File "C:\Users\SD\stable-diffusion-webui\extensions\sd-webui-roop\install.py", line 44, in <module>
    raise e
  File "C:\Users\SD\stable-diffusion-webui\extensions\sd-webui-roop\install.py", line 26, in <module>
    launch.run_pip(
  File "C:\Users\SD\stable-diffusion-webui\modules\launch_utils.py", line 124, in run_pip
    return run(f'"{python}" -m pip {command} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}", live=live)
  File "C:\Users\SD\stable-diffusion-webui\modules\launch_utils.py", line 101, in run
    raise RuntimeError("\n".join(error_bits))
RuntimeError: Couldn't install sd-webui-roop requirement: tensorflow==2.12.0.
Command: "C:\Users\SD\stable-diffusion-webui\venv\Scripts\python.exe" -m pip install tensorflow==2.12.0 --prefer-binary
Error code: 1
stdout: Collecting tensorflow==2.12.0
  Using cached tensorflow-2.12.0-cp310-cp310-win_amd64.whl (1.9 kB)
Requirement already satisfied: tensorflow-intel==2.12.0 in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from tensorflow==2.12.0) (2.12.0)
Requirement already satisfied: absl-py>=1.0.0 in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0) (1.6.3)
Requirement already satisfied: flatbuffers>=2.0 in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0) (23.3.3)
Requirement already satisfied: gast<=0.4.0,>=0.2.1 in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0) (0.4.0)
Requirement already satisfied: google-pasta>=0.1.1 in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0) (0.2.0)
Requirement already satisfied: h5py>=2.9.0 in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0) (3.8.0)
Requirement already satisfied: jax>=0.3.15 in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0) (0.4.12)
Requirement already satisfied: libclang>=13.0.0 in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0) (16.0.0)
Requirement already satisfied: numpy<1.24,>=1.22 in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0) (1.23.5)
Requirement already satisfied: opt-einsum>=2.3.2 in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0) (3.3.0)
Requirement already satisfied: packaging in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0) (23.0)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0) (3.20.3)
Requirement already satisfied: setuptools in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0) (67.6.1)
Requirement already satisfied: six>=1.12.0 in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0) (1.16.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0) (2.2.0)
Requirement already satisfied: typing-extensions>=3.6.6 in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0) (4.5.0)
Requirement already satisfied: wrapt<1.15,>=1.11.0 in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0) (1.14.1)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0) (1.51.3)
Collecting tensorboard<2.13,>=2.12 (from tensorflow-intel==2.12.0->tensorflow==2.12.0)
  Using cached tensorboard-2.12.3-py3-none-any.whl (5.6 MB)
Collecting tensorflow-estimator<2.13,>=2.12.0 (from tensorflow-intel==2.12.0->tensorflow==2.12.0)
  Using cached tensorflow_estimator-2.12.0-py2.py3-none-any.whl (440 kB)
Collecting keras<2.13,>=2.12.0 (from tensorflow-intel==2.12.0->tensorflow==2.12.0)
  Using cached keras-2.12.0-py2.py3-none-any.whl (1.7 MB)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0) (0.31.0)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from astunparse>=1.6.0->tensorflow-intel==2.12.0->tensorflow==2.12.0) (0.38.4)
Requirement already satisfied: ml-dtypes>=0.1.0 in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from jax>=0.3.15->tensorflow-intel==2.12.0->tensorflow==2.12.0) (0.2.0)
Requirement already satisfied: scipy>=1.7 in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from jax>=0.3.15->tensorflow-intel==2.12.0->tensorflow==2.12.0) (1.10.1)
Requirement already satisfied: google-auth<3,>=1.6.3 in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0->tensorflow==2.12.0) (2.16.2)
Collecting google-auth-oauthlib<1.1,>=0.5 (from tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0->tensorflow==2.12.0)
  Using cached google_auth_oauthlib-1.0.0-py2.py3-none-any.whl (18 kB)
Requirement already satisfied: markdown>=2.6.8 in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0->tensorflow==2.12.0) (3.4.1)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0->tensorflow==2.12.0) (2.25.1)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0->tensorflow==2.12.0) (0.7.1)
Requirement already satisfied: werkzeug>=1.0.1 in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0->tensorflow==2.12.0) (2.2.3)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0->tensorflow==2.12.0) (5.3.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0->tensorflow==2.12.0) (0.2.8)
Requirement already satisfied: rsa<5,>=3.1.4 in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0->tensorflow==2.12.0) (4.9)
Requirement already satisfied: requests-oauthlib>=0.7.0 in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from google-auth-oauthlib<1.1,>=0.5->tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0->tensorflow==2.12.0) (1.3.1)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0->tensorflow==2.12.0) (4.0.0)
Requirement already satisfied: idna<3,>=2.5 in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0->tensorflow==2.12.0) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0->tensorflow==2.12.0) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0->tensorflow==2.12.0) (2022.12.7)
Requirement already satisfied: MarkupSafe>=2.1.1 in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from werkzeug>=1.0.1->tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0->tensorflow==2.12.0) (2.1.2)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0->tensorflow==2.12.0) (0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in c:\users\sd\stable-diffusion-webui\venv\lib\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.1,>=0.5->tensorboard<2.13,>=2.12->tensorflow-intel==2.12.0->tensorflow==2.12.0) (3.2.2)
Installing collected packages: tensorflow-estimator, keras, google-auth-oauthlib, tensorboard, tensorflow
  Attempting uninstall: tensorflow-estimator
    Found existing installation: tensorflow-estimator 2.10.0
    Uninstalling tensorflow-estimator-2.10.0:
      Successfully uninstalled tensorflow-estimator-2.10.0
  Attempting uninstall: keras
    Found existing installation: keras 2.10.0
    Uninstalling keras-2.10.0:
      Successfully uninstalled keras-2.10.0
  Attempting uninstall: google-auth-oauthlib
    Found existing installation: google-auth-oauthlib 0.4.6
    Uninstalling google-auth-oauthlib-0.4.6:
      Successfully uninstalled google-auth-oauthlib-0.4.6
  Attempting uninstall: tensorboard
    Found existing installation: tensorboard 2.10.1
    Uninstalling tensorboard-2.10.1:
      Successfully uninstalled tensorboard-2.10.1
  Attempting uninstall: tensorflow
    Found existing installation: tensorflow 2.10.1
    Uninstalling tensorflow-2.10.1:
      Successfully uninstalled tensorflow-2.10.1

stderr: ERROR: Could not install packages due to an OSError: [WinError 5]   : 'C:\\Users\\SD\\AppData\\Local\\Temp\\pip-uninstall-dlwz0m5i\\python\\flags_pybind.pyd'
Check the permissions.

**Comment by Benjaminwj** [comment] 2023-06-19 03:06
also this error.

**Comment by s0md3v** [comment] 2023-06-19 05:07
This error is out of scope because you got it while installing a dependency. It's not a bug for me to fix. Use google.

**Closed by s0md3v** 2023-06-19 05:07 UTC
